const canvas=document.getElementById('paint'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const s={acc:{x:0,y:0,z:0},rot:{a:0,b:0,g:0},ori:{a:0,b:0,g:0},heading:0,light:0,lat:0,lon:0,touch:{x:.5,y:.5,active:false},x:.5,y:.5,px:.5,py:.5,t:performance.now(),points:0};
let W=1,H=1,dpr=1,running=false,last=performance.now(),frames=0,fps=0,als=null,sensors=[],rafId=0,gpsWatch=null,starting=false;
let layers=[],activeLayer=0,undoStack=[],redoStack=[],lastCheckpoint=0;
function newLayer(name){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=canvas.width;c.height=canvas.height;x.setTransform(dpr,0,0,dpr,0,0);return{name,canvas:c,ctx:x,opacity:1,locked:false}}
function initLayers(){if(layers.length)return;layers=[newLayer('Capa 1')];renderLayerControls()}
function renderLayerControls(){const sel=$('layerSelect');if(!sel)return;sel.innerHTML='';layers.forEach((l,i)=>{const o=document.createElement('option');o.value=i;o.textContent=l.name+(l.locked?' 🔒':'');sel.appendChild(o)});sel.value=activeLayer;$('layerOpacity').value=layers[activeLayer].opacity;$('layerLocked').checked=layers[activeLayer].locked;$('deleteLayer').disabled=layers.length===1}
function renderLayers(){ctx.clearRect(0,0,W,H);for(const l of layers){ctx.save();ctx.globalAlpha=l.opacity;ctx.drawImage(l.canvas,0,0,W,H);ctx.restore()}}
function snapshot(){return layers.map(l=>({name:l.name,opacity:l.opacity,locked:l.locked,data:l.ctx.getImageData(0,0,l.canvas.width,l.canvas.height)}))}
function checkpoint(){undoStack.push(snapshot());if(undoStack.length>20)undoStack.shift();redoStack=[];lastCheckpoint=performance.now()}
function restoreSnapshot(snap){snap.forEach((x,i)=>{if(!layers[i])layers[i]=newLayer(x.name);const l=layers[i];l.name=x.name;l.opacity=x.opacity;l.locked=x.locked;l.ctx.putImageData(x.data,0,0)});layers.length=snap.length;activeLayer=Math.min(activeLayer,layers.length-1);renderLayerControls();renderLayers()}
function undo(){if(!undoStack.length)return;redoStack.push(snapshot());restoreSnapshot(undoStack.pop())}
function redo(){if(!redoStack.length)return;undoStack.push(snapshot());restoreSnapshot(redoStack.pop())}
function activeCtx(){const l=layers[activeLayer];return l&&!l.locked?l.ctx:null}



let cameraStream=null,cameraFacing='environment';
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}$('cameraVideo').srcObject=null;$('cameraSwitch').disabled=true;$('cameraStatus').textContent='Cámara inactiva';$('cameraToggle').textContent='Activar cámara';renderLayers()}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){$('cameraStatus').textContent='Cámara no disponible en este navegador';return}try{if(cameraStream)stopCamera();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:cameraFacing}},audio:false});const v=$('cameraVideo');v.srcObject=cameraStream;await v.play();$('cameraSwitch').disabled=false;$('cameraToggle').textContent='Desactivar cámara';$('cameraStatus').textContent='Cámara activa';}catch(e){cameraStream=null;$('cameraStatus').textContent='Permiso de cámara denegado o cámara no disponible'}}
async function switchCamera(){cameraFacing=cameraFacing==='environment'?'user':'environment';await startCamera()}

const PRESET_KEY='sensor-painter-presets-v1';
function readPresets(){try{return JSON.parse(localStorage.getItem(PRESET_KEY)||'{}')}catch(e){return{}}}
function writePresets(data){localStorage.setItem(PRESET_KEY,JSON.stringify(data))}
function presetState(){return{brush:$('brush').value,color:$('color').value,size:$('size').value,opacity:$('opacity').value,driver:$('driver').value,effect:$('effect').value,sensitivity:$('sensitivity').value,speed:$('speed').value,activeLayer,layers:layers.map(l=>({name:l.name,opacity:l.opacity,locked:l.locked,data:l.canvas.toDataURL('image/png')}))}}
function renderPresets(selected=''){const sel=$('presetSelect');if(!sel)return;const presets=readPresets();sel.innerHTML='<option value="">— Seleccionar —</option>';Object.keys(presets).sort().forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;sel.appendChild(o)});sel.value=selected}
function savePreset(){const name=$('presetName').value.trim();if(!name){$('presetName').focus();return}try{const presets=readPresets();presets[name]=presetState();writePresets(presets);renderPresets(name);$('status').textContent='Preset guardado: '+name}catch(e){$('status').textContent='No se pudo guardar el preset (espacio local insuficiente)'}}
function loadPreset(){const name=$('presetSelect').value;if(!name)return;const preset=readPresets()[name];if(!preset||!Array.isArray(preset.layers))return;checkpoint();$('brush').value=preset.brush||$('brush').value;$('color').value=preset.color||$('color').value;$('size').value=preset.size||$('size').value;$('opacity').value=preset.opacity||$('opacity').value;$('driver').value=preset.driver||$('driver').value;$('effect').value=preset.effect||$('effect').value;$('sensitivity').value=preset.sensitivity||$('sensitivity').value;$('speed').value=preset.speed||$('speed').value;layers=preset.layers.map(x=>newLayer(x.name||'Capa'));layers.forEach((l,i)=>{l.opacity=Number.isFinite(preset.layers[i].opacity)?preset.layers[i].opacity:1;l.locked=!!preset.layers[i].locked;const img=new Image();img.onload=()=>{l.ctx.clearRect(0,0,W,H);l.ctx.drawImage(img,0,0,W,H);renderLayers()};img.src=preset.layers[i].data});activeLayer=Math.min(Math.max(0,preset.activeLayer||0),layers.length-1);undoStack=[];redoStack=[];renderLayerControls();renderLayers();$('status').textContent='Preset cargado: '+name}
function deletePreset(){const name=$('presetSelect').value;if(!name)return;const presets=readPresets();delete presets[name];writePresets(presets);renderPresets();$('status').textContent='Preset eliminado: '+name}

const sensorStatus={motion:'no iniciado',orientation:'no iniciado',gps:'no iniciado',light:'no disponible',accelerometer:'no disponible',gyroscope:'no disponible',magnetometer:'no disponible'};
function renderSensorStatus(){$('sensorStatus').textContent=Object.entries(sensorStatus).map(([k,v])=>k+': '+v).join('\\n')}
function resize(){const r=canvas.getBoundingClientRect();const old=layers.map(l=>l.ctx.getImageData(0,0,l.canvas.width,l.canvas.height));dpr=Math.min(devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);layers.forEach((l,i)=>{l.canvas.width=canvas.width;l.canvas.height=canvas.height;l.ctx.setTransform(dpr,0,0,dpr,0,0);if(old[i])l.ctx.putImageData(old[i],0,0)});renderLayers()} addEventListener('resize',resize);resize();initLayers();checkpoint();
const num=(v,d=0)=>Number.isFinite(v)?v:d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function paintPoint(x,y,dx,dy){const p=activeCtx();if(!p)return;const b=$('brush').value,c=num(parseFloat($('size').value),20),op=num(parseFloat($('opacity').value),.7),col=$('color').value;p.save();p.globalAlpha=op;p.lineCap='round';p.lineJoin='round';
if(b==='ink'){p.fillStyle=col;p.beginPath();p.arc(x,y,c*.5,0,7);p.fill()}
if(b==='spray'){p.fillStyle=col;for(let i=0;i<18;i++){const a=Math.random()*7,r=Math.random()*c*1.8;p.globalAlpha=op*(1-r/(c*1.8))*.7;p.beginPath();p.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,Math.max(.5,c*.025),0,7);p.fill()}}
if(b==='ribbon'){p.strokeStyle=col;p.lineWidth=c;p.beginPath();p.moveTo(s.px*W,s.py*H);p.quadraticCurveTo((s.px*W+x)/2+dy*c,(s.py*H+y)/2-dx*c,x,y);p.stroke()}
if(b==='glow'){const g=p.createRadialGradient(x,y,0,x,y,c*3);g.addColorStop(0,col);g.addColorStop(1,'transparent');p.fillStyle=g;p.globalAlpha=op*.8;p.beginPath();p.arc(x,y,c*3,0,7);p.fill()}
if(b==='dots'){p.fillStyle=col;for(let i=0;i<5;i++){const a=i*1.256;p.globalAlpha=op*(1-i*.12);p.beginPath();p.arc(x+Math.cos(a)*c,y+Math.sin(a)*c,c*.18,0,7);p.fill()}}
if(b==='wash'){p.fillStyle=col;for(let i=0;i<4;i++){p.globalAlpha=op*.12;p.beginPath();p.arc(x+(Math.random()-.5)*c,y+(Math.random()-.5)*c,c*(.7+Math.random()*.8),0,7);p.fill()}}
p.restore();s.points++}
function draw(x,y){const dx=x-s.x,dy=y-s.y,e=$('effect').value;
if(e==='fade'){ctx.save();ctx.globalAlpha=.035;ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);ctx.restore()}
if(e==='mirror'){paintPoint(W-x,y,dx,dy);paintPoint(x,H-y,dx,dy);paintPoint(W-x,H-y,dx,dy)}
if(e==='orbit'){const cx=W/2,cy=H/2,a=.018*(parseFloat($('speed').value)||1),co=Math.cos(a),si=Math.sin(a),ox=x-cx,oy=y-cy;paintPoint(cx+ox*co-oy*si,cy+ox*si+oy*co,dx,dy)}
if(e==='chaos'){x+=(Math.random()-.5)*W*.05;y+=(Math.random()-.5)*H*.05}
paintPoint(x,y,dx,dy);if(e==='trail'){paintPoint(x-dx*8,y-dy*8,dx,dy);paintPoint(x-dx*18,y-dy*18,dx,dy)}s.px=s.x;s.py=s.y;s.x=x/W;s.y=y/H}
function drive(){const k=parseFloat($('sensitivity').value)||1,d=$('driver').value,a=s.acc,o=s.ori;let x=.5,y=.5;
if(d==='motion'){x=.5+clamp(a.x*k/25,-.48,.48);y=.5-clamp(a.y*k/25,-.48,.48)}
if(d==='tilt'){x=.5+clamp((o.g||0)/90*k,-.48,.48);y=.5+clamp((o.b||0)/180*k,-.48,.48)}
if(d==='heading'){x=(s.heading%360)/360;y=.5+clamp(Math.sin((s.heading||0)*Math.PI/180)*.45,-.48,.48)}
if(d==='geo'){x=.5+Math.sin(s.lon*Math.PI/180)*.45;y=.5-Math.sin(s.lat*Math.PI/180)*.45}
if(d==='light'){x=.5+clamp(s.light/1000-.5,-.48,.48);y=.5-clamp(s.light/1000-.5,-.48,.48)}
if(d==='touch'){x=s.touch.active?s.touch.x:.5+clamp(a.x*k/30,-.48,.48);y=s.touch.active?s.touch.y:.5-clamp(a.y*k/30,-.48,.48)}
return[clamp(x,0,1),clamp(y,0,1)]}
function startLoop(){if(!rafId)rafId=requestAnimationFrame(frame)}
function frame(t){rafId=0;if(!running&&!s.touch.active)return;if(performance.now()-lastCheckpoint>750)checkpoint();if(t-last<16){startLoop();return}last=t;frames++;if(t-s.t>1000){fps=frames*1000/(t-s.t);frames=0;s.t=t;$('fps').textContent=Math.round(fps)+' FPS';$('telemetry').textContent='acc  '+s.acc.x.toFixed(2)+' '+s.acc.y.toFixed(2)+' '+s.acc.z.toFixed(2)+'\nrot  '+s.rot.a.toFixed(1)+' '+s.rot.b.toFixed(1)+' '+s.rot.g.toFixed(1)+'\nori  '+s.ori.a.toFixed(1)+' '+s.ori.b.toFixed(1)+' '+s.ori.g.toFixed(1)+'\nheading '+s.heading.toFixed(1)+'°\nlight '+(s.light?s.light.toFixed(1):'—')+' lx\nGPS '+(s.lat?s.lat.toFixed(4):'—')+', '+(s.lon?s.lon.toFixed(4):'—')+'\ntrazos '+s.points;$('sensorState').textContent=running?'Sensores activos':'Modo táctil'}const p=drive();draw(p[0]*W,p[1]*H);renderLayers();startLoop()}function motion(e){const a=e.accelerationIncludingGravity||e.acceleration;s.acc={x:num(a&&a.x),y:num(a&&a.y),z:num(a&&a.z)};const r=e.rotationRate;s.rot={a:num(r&&r.alpha),b:num(r&&r.beta),g:num(r&&r.gamma)}}
function orientation(e){s.ori={a:num(e.alpha),b:num(e.beta),g:num(e.gamma)};s.heading=num(e.webkitCompassHeading,num(e.alpha));}
function touch(ev){const r=canvas.getBoundingClientRect();s.touch={x:clamp((ev.clientX-r.left)/r.width,0,1),y:clamp((ev.clientY-r.top)/r.height,0,1),active:true}}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture&&canvas.setPointerCapture(e.pointerId);touch(e);startLoop()});canvas.addEventListener('pointermove',e=>{if(e.buttons)touch(e)});canvas.addEventListener('pointerup',()=>s.touch.active=false);
function stopSensors(){running=false;starting=false;if(gpsWatch!==null&&navigator.geolocation){navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null}removeEventListener('devicemotion',motion);removeEventListener('deviceorientation',orientation);for(const q of sensors){try{q.stop()}catch(e){}}sensors=[];if(als){try{als.stop()}catch(e){}als=null}for(const k of Object.keys(sensorStatus))sensorStatus[k]='detenido';renderSensorStatus();$('sensorState').textContent=s.touch.active?'Modo táctil':'Sin sensores';$('status').textContent='Sensores detenidos';$('activate').textContent='Activar sensores'}
async function requestSensors(){if(starting)return;if(running){stopSensors();return}starting=true;let ok=0;
try{if(typeof DeviceMotionEvent==='undefined'){sensorStatus.motion='no disponible'}else if(typeof DeviceMotionEvent.requestPermission==='function'){if(await DeviceMotionEvent.requestPermission()==='granted'){addEventListener('devicemotion',motion);sensorStatus.motion='activo';ok++}else sensorStatus.motion='permiso denegado'}else{addEventListener('devicemotion',motion);sensorStatus.motion='disponible';ok++}}catch(e){sensorStatus.motion='error'}
try{if(typeof DeviceOrientationEvent==='undefined'){sensorStatus.orientation='no disponible'}else if(typeof DeviceOrientationEvent.requestPermission==='function'){if(await DeviceOrientationEvent.requestPermission()==='granted'){addEventListener('deviceorientation',orientation);sensorStatus.orientation='activo';ok++}else sensorStatus.orientation='permiso denegado'}else{addEventListener('deviceorientation',orientation);sensorStatus.orientation='disponible';ok++}}catch(e){sensorStatus.orientation='error'}
if(navigator.geolocation){sensorStatus.gps='esperando permiso';gpsWatch=navigator.geolocation.watchPosition(p=>{s.lat=p.coords.latitude;s.lon=p.coords.longitude;sensorStatus.gps='activo'},()=>{sensorStatus.gps='permiso denegado o error'})}else sensorStatus.gps='no disponible';
if('AmbientLightSensor'in window){try{als=new AmbientLightSensor();als.addEventListener('reading',()=>s.light=als.illuminance);als.start();sensorStatus.light='activo';ok++}catch(e){sensorStatus.light='error o permiso denegado'}}
for(const item of [['Accelerometer','accel'],['Gyroscope','gyro'],['Magnetometer','mag']]){const Type=item[0],key=item[1],name=key==='accel'?'accelerometer':key==='gyro'?'gyroscope':'magnetometer';if(Type in window){try{const q=new window[Type]({frequency:30});q.addEventListener('reading',()=>{if(key==='accel')s.acc={x:num(q.x),y:num(q.y),z:num(q.z)};if(key==='gyro')s.rot={a:num(q.x)*57.3,b:num(q.y)*57.3,g:num(q.z)*57.3};if(key==='mag')s.heading=(Math.atan2(q.y,q.x)*180/Math.PI+360)%360});q.start();sensors.push(q);sensorStatus[name]='activo';ok++}catch(e){sensorStatus[name]='error o permiso denegado'}}else sensorStatus[name]='no disponible'}
starting=false;running=ok>0;renderSensorStatus();if(running)startLoop();$('status').textContent=ok?'Sensores activos: '+ok:'Sin sensores activos';$('activate').textContent=running?'Detener sensores':'Activar sensores'}
}
$('cameraToggle').addEventListener('click',()=>cameraStream?stopCamera():startCamera());$('cameraSwitch').addEventListener('click',switchCamera);$('cameraMirror').addEventListener('change',renderLayers);
$('presetSave').addEventListener('click',savePreset);$('presetLoad').addEventListener('click',loadPreset);$('presetDelete').addEventListener('click',deletePreset);renderPresets();
$('activate').addEventListener('click',requestSensors);$('clear').addEventListener('click',()=>{const p=activeCtx();if(!p)return;checkpoint();p.clearRect(0,0,W,H);s.points=0;renderLayers()});$('undo').addEventListener('click',undo);$('redo').addEventListener('click',redo);$('layerSelect').addEventListener('change',e=>{activeLayer=Number(e.target.value);renderLayerControls()});$('layerOpacity').addEventListener('input',e=>{layers[activeLayer].opacity=parseFloat(e.target.value);renderLayers()});$('layerLocked').addEventListener('change',e=>{checkpoint();layers[activeLayer].locked=e.target.checked;renderLayerControls()});$('addLayer').addEventListener('click',()=>{checkpoint();layers.push(newLayer('Capa '+(layers.length+1)));activeLayer=layers.length-1;renderLayerControls();renderLayers()});$('deleteLayer').addEventListener('click',()=>{if(layers.length===1)return;checkpoint();layers.splice(activeLayer,1);activeLayer=Math.max(0,activeLayer-1);renderLayerControls();renderLayers()});$('save').addEventListener('click',()=>{const a=document.createElement('a');a.download='sensor-painting-'+Date.now()+'.png';a.href=canvas.toDataURL('image/png');a.click()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});